{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "deployment-inspector.fullname" . }}
  labels:
    {{- include "deployment-inspector.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  suspend: {{ .Values.cronjob.suspend }}
  jobTemplate:
    spec:
      {{- if .Values.cronjob.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ .Values.cronjob.ttlSecondsAfterFinished }}
      {{- end }}
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "deployment-inspector.selectorLabels" . | nindent 12 }}
            {{- with .Values.labels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.annotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "deployment-inspector.serviceAccountName" . }}
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          containers:
          - name: {{ .Chart.Name }}
            {{- with .Values.securityContext }}
            securityContext:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.Version }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- if eq .Values.deploymentInspector.command "list" }}
            command:
            - ./deployment-inspector
            - list
            - {{ required "deploymentInspector.deploymentName is required" .Values.deploymentInspector.deploymentName | quote }}
            - "--namespace"
            - {{ .Values.deploymentInspector.namespace | quote }}
            {{- else if eq .Values.deploymentInspector.command "run-job" }}
            command:
            - ./deployment-inspector
            - run-job
            - {{ required "deploymentInspector.deploymentName is required" .Values.deploymentInspector.deploymentName | quote }}
            - {{ .Values.deploymentInspector.job.namePrefix | quote }}
            - "--namespace"
            - {{ .Values.deploymentInspector.namespace | quote }}
            {{- if .Values.deploymentInspector.job.namespace }}
            - "--job-namespace"
            - {{ .Values.deploymentInspector.job.namespace | quote }}
            {{- end }}
            - "--image"
            - {{ .Values.deploymentInspector.job.image | quote }}
            {{- if .Values.deploymentInspector.job.command }}
            - "--command"
            - {{ join "," .Values.deploymentInspector.job.command | quote }}
            {{- end }}
            {{- if .Values.deploymentInspector.job.tolerations }}
            - "--tolerations"
            {{- if kindIs "string" .Values.deploymentInspector.job.tolerations }}
            - {{ .Values.deploymentInspector.job.tolerations | quote }}
            {{- else }}
            - {{ .Values.deploymentInspector.job.tolerations | toJson | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- with .Values.env }}
            env:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}